package com.wally.customersupport.agent.application.activation;

public enum AgentActivationMutationReason {
    ACTIVATION_PERSISTED,
    KILL_SWITCH_PERSISTED,
    ROLLBACK_PERSISTED,
    FEATURE_DISABLED,
    AUTHORIZATION_DENIED,
    VERSION_NOT_FOUND,
    ACTIVATION_NOT_FOUND,
    PREVIOUS_VERSION_NOT_FOUND,
    INVALID_REQUEST,
    IDEMPOTENCY_ALREADY_CLAIMED,
    IDEMPOTENCY_GUARD_FAILED,
    REGISTRY_FAILED
}
