package com.wally.customersupport.agent.application.service;

import java.util.LinkedHashMap;
import java.util.Map;

import com.wally.customersupport.catalog.application.service.CatalogSearchResult;
import com.wally.customersupport.conversation.application.tool.CatalogSearchTool;
import com.wally.customersupport.conversation.application.tool.WcsToolRegistry;
import com.wally.customersupport.shared.infrastructure.observability.StructuredEventLog;
import org.springframework.beans.factory.annotation.Autowired;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Executes the catalog specialist through a fixed, deterministic capability.
 *
 * <p>This is deliberately not a generic model runner. The active definition
 * can authorize the {@code catalog.search} capability, but the capability
 * itself delegates to the existing bounded catalog application service. No
 * SQL, prompt, or catalog fact is generated by an LLM in this boundary.</p>
 */
@Service
@Slf4j
public class CatalogSpecialistExecutor {

    public static final String AGENT_ID = "catalog-specialist";
    public static final String CATALOG_SEARCH_TOOL = "catalog.search";
    private static final String USE_CASE = "CATALOG_SEARCH";

    private final WcsToolRegistry toolRegistry;

    @Autowired
    public CatalogSpecialistExecutor(WcsToolRegistry toolRegistry) {
        this.toolRegistry = toolRegistry;
    }

    public CatalogSpecialistExecutionResult execute(CatalogSpecialistExecutionRequest request) {
        long startedAt = System.nanoTime();
        AgentRuntimeDefinition definition = request.definition();
        if (!AGENT_ID.equals(definition.agentId())) {
            return fallback(request, "AGENT_NOT_SUPPORTED", startedAt);
        }
        if (!definition.allowedTools().contains(CATALOG_SEARCH_TOOL)) {
            return fallback(request, "TOOL_NOT_ALLOWED", startedAt);
        }

        CatalogSearchTool tool = toolRegistry.find(CATALOG_SEARCH_TOOL, CatalogSearchTool.class)
                .orElse(null);
        if (tool == null) {
            return fallback(request, "TOOL_NOT_REGISTERED", startedAt);
        }

        try {
            StructuredEventLog.info(log, "AGENT_TOOL_EXECUTION_STARTED",
                    fields(request, "STARTED", "EXECUTING", null, startedAt));
            return tool.execute(new CatalogSearchTool.Input(
                            request.catalogQuery(),
                            request.recentMessages(),
                            request.latestMessage()))
                    .map(result -> completed(request, result, startedAt))
                    .orElseGet(() -> fallback(request, "NO_RESPONSE", startedAt));
        } catch (RuntimeException exception) {
            Map<String, Object> fields = fields(request, "FAILED", "EXECUTION_FAILED", null, startedAt);
            fields.put("errorType", exception.getClass().getSimpleName());
            StructuredEventLog.warn(log, "AGENT_SPECIALIST_EXECUTION_FAILED", fields);
            return new CatalogSpecialistExecutionResult(
                    CatalogSpecialistExecutionResult.Status.FALLBACK,
                    "EXECUTION_FAILED",
                    null,
                    elapsedMillis(startedAt));
        }
    }

    private CatalogSpecialistExecutionResult completed(
            CatalogSpecialistExecutionRequest request,
            CatalogSearchResult structuredResult,
            long startedAt) {
        CatalogSpecialistExecutionResult result = new CatalogSpecialistExecutionResult(
                CatalogSpecialistExecutionResult.Status.EXECUTED,
                "EXECUTED",
                structuredResult,
                elapsedMillis(startedAt));
        StructuredEventLog.info(log, "AGENT_SPECIALIST_EXECUTION_COMPLETED",
                fields(request, result.status().name(), result.reason(), structuredResult, startedAt));
        StructuredEventLog.info(log, "AGENT_TOOL_EXECUTION_COMPLETED",
                fields(request, result.status().name(), result.reason(), structuredResult, startedAt));
        return result;
    }

    private CatalogSpecialistExecutionResult fallback(
            CatalogSpecialistExecutionRequest request,
            String reason,
            long startedAt) {
        CatalogSpecialistExecutionResult result = new CatalogSpecialistExecutionResult(
                CatalogSpecialistExecutionResult.Status.FALLBACK,
                reason,
                null,
                elapsedMillis(startedAt));
        StructuredEventLog.info(log, "AGENT_SPECIALIST_EXECUTION_FALLBACK",
                fields(request, result.status().name(), result.reason(), null, startedAt));
        StructuredEventLog.info(log, "AGENT_TOOL_EXECUTION_FALLBACK",
                fields(request, result.status().name(), result.reason(), null, startedAt));
        return result;
    }

    private static Map<String, Object> fields(
            CatalogSpecialistExecutionRequest request,
            String outcome,
            String reason,
            CatalogSearchResult result,
            long startedAt) {
        Map<String, Object> fields = new LinkedHashMap<>();
        fields.put("agentId", request.definition().agentId());
        fields.put("agentVersion", request.definition().agentVersion());
        fields.put("useCase", USE_CASE);
        fields.put("executionMode", "DETERMINISTIC_TOOL");
        fields.put("toolName", CatalogSearchTool.NAME);
        fields.put("inputSchemaVersion", CatalogSearchTool.DESCRIPTOR.inputSchemaVersion());
        fields.put("outputSchemaVersion", CatalogSearchTool.DESCRIPTOR.outputSchemaVersion());
        fields.put("outcome", outcome);
        fields.put("reason", reason);
        fields.put("resultStatus", result == null ? "FALLBACK" : result.status().name());
        fields.put("resultCount", result == null ? 0 : result.resultCount());
        fields.put("durationMs", elapsedMillis(startedAt));
        return fields;
    }

    private static long elapsedMillis(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000;
    }
}
