package com.wally.customersupport.agent.application.service;

import java.util.LinkedHashMap;
import java.util.Map;

import com.wally.customersupport.catalog.application.service.CatalogConversationService;
import com.wally.customersupport.shared.infrastructure.observability.StructuredEventLog;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Executes the catalog specialist through a fixed, deterministic capability.
 *
 * <p>This is deliberately not a generic model runner. The active definition
 * can authorize the {@code catalog.search} capability, but the capability
 * itself delegates to the existing bounded catalog application service. No
 * SQL, prompt, or catalog fact is generated by an LLM in this boundary.</p>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class CatalogSpecialistExecutor {

    public static final String AGENT_ID = "catalog-specialist";
    public static final String CATALOG_SEARCH_TOOL = "catalog.search";
    private static final String USE_CASE = "CATALOG_SEARCH";

    private final CatalogConversationService catalogConversationService;

    public CatalogSpecialistExecutionResult execute(CatalogSpecialistExecutionRequest request) {
        long startedAt = System.nanoTime();
        AgentRuntimeDefinition definition = request.definition();
        if (!AGENT_ID.equals(definition.agentId())) {
            return fallback(request, "AGENT_NOT_SUPPORTED", startedAt);
        }
        if (!definition.allowedTools().contains(CATALOG_SEARCH_TOOL)) {
            return fallback(request, "TOOL_NOT_ALLOWED", startedAt);
        }

        try {
            return catalogConversationService.replyFor(
                            request.catalogQuery(),
                            request.recentMessages(),
                            request.latestMessage())
                    .filter(response -> !response.isBlank())
                    .map(response -> completed(request, response, startedAt))
                    .orElseGet(() -> fallback(request, "NO_RESPONSE", startedAt));
        } catch (RuntimeException exception) {
            Map<String, Object> fields = fields(request, "FAILED", "EXECUTION_FAILED", startedAt);
            fields.put("errorType", exception.getClass().getSimpleName());
            StructuredEventLog.warn(log, "AGENT_SPECIALIST_EXECUTION_FAILED", fields);
            return new CatalogSpecialistExecutionResult(
                    CatalogSpecialistExecutionResult.Status.FALLBACK,
                    "EXECUTION_FAILED",
                    null,
                    elapsedMillis(startedAt));
        }
    }

    private CatalogSpecialistExecutionResult completed(
            CatalogSpecialistExecutionRequest request,
            String response,
            long startedAt) {
        CatalogSpecialistExecutionResult result = new CatalogSpecialistExecutionResult(
                CatalogSpecialistExecutionResult.Status.EXECUTED,
                "EXECUTED",
                response,
                elapsedMillis(startedAt));
        StructuredEventLog.info(log, "AGENT_SPECIALIST_EXECUTION_COMPLETED",
                fields(request, result.status().name(), result.reason(), startedAt));
        return result;
    }

    private CatalogSpecialistExecutionResult fallback(
            CatalogSpecialistExecutionRequest request,
            String reason,
            long startedAt) {
        CatalogSpecialistExecutionResult result = new CatalogSpecialistExecutionResult(
                CatalogSpecialistExecutionResult.Status.FALLBACK,
                reason,
                null,
                elapsedMillis(startedAt));
        StructuredEventLog.info(log, "AGENT_SPECIALIST_EXECUTION_FALLBACK",
                fields(request, result.status().name(), result.reason(), startedAt));
        return result;
    }

    private static Map<String, Object> fields(
            CatalogSpecialistExecutionRequest request,
            String outcome,
            String reason,
            long startedAt) {
        Map<String, Object> fields = new LinkedHashMap<>();
        fields.put("agentId", request.definition().agentId());
        fields.put("agentVersion", request.definition().agentVersion());
        fields.put("useCase", USE_CASE);
        fields.put("executionMode", "DETERMINISTIC_TOOL");
        fields.put("outcome", outcome);
        fields.put("reason", reason);
        fields.put("durationMs", elapsedMillis(startedAt));
        return fields;
    }

    private static long elapsedMillis(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000;
    }
}
