package com.wally.customersupport.agent.application.registry;

public enum AgentRegistryMutationReason {
    DRAFT_PERSISTED,
    VERSION_CLONED,
    LIFECYCLE_TRANSITIONED,
    FEATURE_DISABLED,
    AUTHORIZATION_DENIED,
    VERSION_NOT_FOUND,
    VERSION_ALREADY_EXISTS,
    INVALID_REQUEST,
    INVALID_LIFECYCLE_TARGET,
    APPROVAL_REFERENCES_REQUIRED,
    EVALUATION_EVIDENCE_REQUIRED,
    EVALUATION_RUN_NOT_FOUND,
    EVALUATION_RUNS_NOT_COMPARABLE,
    EVALUATION_CANDIDATE_VERSION_MISMATCH,
    EVALUATION_BASELINE_NOT_ACTIVE,
    EVALUATION_DATASET_MISMATCH,
    IDEMPOTENCY_ALREADY_CLAIMED,
    IDEMPOTENCY_GUARD_FAILED,
    LIFECYCLE_CHANGED_CONCURRENTLY,
    REGISTRY_FAILED
}
