package com.wally.customersupport.agent.application.registry;

public enum AgentRegistryMutationReason {
    DRAFT_PERSISTED,
    VERSION_CLONED,
    LIFECYCLE_TRANSITIONED,
    FEATURE_DISABLED,
    AUTHORIZATION_DENIED,
    VERSION_NOT_FOUND,
    VERSION_ALREADY_EXISTS,
    INVALID_REQUEST,
    INVALID_LIFECYCLE_TARGET,
    APPROVAL_REFERENCES_REQUIRED,
    IDEMPOTENCY_ALREADY_CLAIMED,
    IDEMPOTENCY_GUARD_FAILED,
    LIFECYCLE_CHANGED_CONCURRENTLY,
    REGISTRY_FAILED
}
