-- Baseline metadata only. The runtime activation gate remains disabled by default
-- and no activation pointer is created by this migration.
insert into wcs.agent_versions (
    id,
    agent_id,
    agent_version,
    name,
    purpose,
    state,
    model_provider,
    model_id,
    temperature,
    top_p,
    system_prompt_version,
    system_prompt_hash,
    input_schema_version,
    output_schema_version,
    allowed_tools,
    knowledge_sources,
    memory_policy,
    response_policy,
    timeout_ms,
    max_steps,
    max_input_tokens,
    max_output_tokens,
    budget_limit_usd,
    fallback_agent_id,
    evaluation_suite_version,
    created_by,
    created_at,
    approved_by,
    approved_at
) values (
    '00000000-0000-0000-0000-000000000901',
    'catalog-specialist',
    1,
    'Catalog specialist baseline',
    'Search products, variants, price and stock through validated WCS tools',
    'APPROVED',
    'wcs',
    'deterministic-tool-v1',
    0.000,
    1.000,
    'system-v1',
    '7b791651bc2e74d37ced276deb5fa48f425a382997db3fe67c83bc7f7a855811',
    'catalog-input-v1',
    'catalog-output-v1',
    '["catalog.search", "catalog.stock"]'::jsonb,
    '[]'::jsonb,
    'conversation-summary-v1',
    'grounded-customer-support-v1',
    10000,
    2,
    2000,
    1000,
    0.050000,
    null,
    'catalog-response-v1',
    'system-migration',
    timestamp with time zone '2026-09-08 12:00:00+00',
    'system-migration',
    timestamp with time zone '2026-09-08 12:00:00+00'
)
on conflict (agent_id, agent_version) do nothing;

-- Rollback: delete only this immutable baseline row after confirming that no
-- activation or runtime reference depends on it. Never modify V9 or V11.
